Resources:
  MainBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.prefix}-main
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 1
            Prefix: "videos/"
            Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000
